name: Pylint Analysis

on:
  push:
    branches:
      - main  # Проверяем только ветку main

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install pylint
    - name: Run Pylint
      run: |
        pylint --score=y $(git ls-files '*.py') | \
          grep -Eo 'Your code has been rated at ([0-9.]+)/10' | \
          awk '{print $1}' > pylint_score.txt 
    - name: Check Pylint score
      run: |
        pylint_score=$(cat pylint_score.txt)
        if [ $(echo "$pylint_score > 8.5" | bc -l) -eq 1 ]; then
          echo "Проверка прошла успешно! Оценка Pylint: $pylint_score"
        else
          echo "Пересмотрите код! Оценка Pylint: $pylint_score"
          exit 1
        fi
